apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-boot-k8s-service
  name: spring-boot-k8s-service
  namespace: example-k8s
spec:
  ports:
  - nodePort: 30001 # Access Port
    port: 9977 # Maaping port with container
    protocol: TCP
    targetPort: 9977
  selector:
    app: spring-boot-k8s
  type: NodePort